### ISSUE TITLE
[RFC] Monorepo

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#703]
## Suggested technology

Circuit UI has grown from a single package (`@sumup/circuit-ui`) into an **ecosystem** of packages ([`@sumup/design-tokens`](https://www.npmjs.com/package/@sumup/design-tokens), [`@sumup/icons`](https://www.npmjs.com/package/@sumup/icons)). Each package currently lives in its own repository. In the review process for open-sourcing the new subpackages, @danpersa proposed to combine all packages in a single **monorepo**.

This would offer several benefits:

- **Community management**: Issues, bug reports, and feature requests would be filed in one place where they can be easily searched and triaged. 
- **Coordinated releases**: Sometimes, a task requires changes in multiple packages. In a monorepo, related changes can be done in one commit and one PR which simplifies code review and the coordination of the release.
- **Centralized documentation**: Having a single place for documentation of all packages makes it easier for users to learn about the ecosystem and how the packages relate to each other. [`@sumup/icons`](https://www.npmjs.com/package/@sumup/icons) is already documented in the Storybook of the component library, however, the list of icons must be kept up-to-date manually.

### Folder Structure

The packages would live in a folder aptly called `packages`. The Storybook configuration, general documentation, and shared linting configuration files would live on the top level of the repository.

```sh
├── .storybook/
├── docs/
├── packages/
│   ├── cli/
│   ├── circuit-ui/
│   ├── design-tokens/
│   └── icons/
├── prettier.config.js
├── README.md
└── ...
```

Each package would contain its source code, testing & build configs, and a separate README.

```sh
components/
├── src/
├── jest.config.json
├── tsconfig.json
├── README.md
└── ...
```

### Tooling

Monorepos add some complexity when it comes to shared tooling and dependency management. These tools are here to help:

#### [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces)

`yarn`, our package manager of choice, has built-in support for monorepos. Each package is a "workspace" and `yarn` can deduplicate dependencies between them. More importantly, packages can depend on _each other_ and always use the latest version.

#### [lerna](https://lerna.js.org/)

Lerna builds on top of `yarn workspaces` to provide additional tools and commands to manage a monorepo, e.g. running a package script (e.g. `yarn test`) in each package. It supports publishing as well, but doesn't handle release notes, which is why I propose to use another tool for that (see below 👇).

### Release Process

We currently use [`semantic-release`](https://github.com/semantic-release/semantic-release/) to automate our publishing and release note generation. `semantic-release` assumes a one-to-one relationship between a Git repository and NPM package. It relies on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to work, but in a monorepo, it would be unable to determine which commit affects which package. 

#### [`changesets`](https://github.com/atlassian/changesets)

I propose to use Atlassian's `changesets` tool instead. It enables the same release automation as `semantic-release` but with an explicit focus on monorepos. Some of its differences are:

- **No enforced commit message format**: While `semantic-release` requires [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to infer the version type and changelog from the commit history, `changesets` creates the changelog based on files that are checked into git. 
- **More control over releases**: `semantic-release` publishes a new release for (almost) every commit, which can flood the release log. `changesets` publishes a new release only when it's asked to, allowing us to group changes together.

## Alternatives

The alternative would be to keep one repository for each package. As the ecosystem grows, maintenance and community management would become more difficult.

## Potential downsides

Monorepos come with additional complexity and require additional tooling to work well. I believe the initial investment pays off over the long run.

It becomes harder to tell issues/PRs/changelogs/etc apart. Which one refers to which package?

As the repository and its git history grow, it takes longer to clone it and set it up locally, which could discourage contributions.

**Comment by robinmetral** [comment]
Thanks for the crystal-clear proposal @connor-baer! 💎 

I like the idea, and monorepos have obvious benefits. I've had some issues with them in the past on the tooling side of things, but it was a while ago and the ecosystem around them has probably evolved by now. `changesets` looks good!.

One thing I don't agree with so much is the move away from conventional commits and "unemotional releases". This should be another RFC in my opinion, because I personally see some benefits to having a commit convention and fully automated releases: it completely removes the cognitive load of having to deal with them. I'm happy to hear more thoughts about this 🙂

**Comment by cyrilchapon** [comment]
Additionally, may be related; every link to sumup-oss/design-tokens in the docs are broken.

**Comment by robinmetral** [comment]
@cyrilchapon thanks for reporting – this might have been fixed by moving to a monorepo but we can fix it before that 🙂 
👉 #709

**Comment by letanure** [comment]
I'm thinking about the structure and why we have separate repos for each part, but in general, I prefer the monorepo, but don't like the idea of just put them together with separate build systems. I think its better go for something simpler, like

```
├── .storybook/
├── docs/
├── src/
│   ├── cli/
│   ├── components/ (with icons)
│   ├── config (former design-tokens)
├── prettier.config.js
├── README.md
└── ...
```

and if we need to have partial exports, like only icons or the design tokens, do this programmatically.
right now, will be just put 3 projects together, will save just the effort to keep track of 3 reps, but the pain point of 3 separate build systems, logs, dependencies, will be the same.

but I need to understand better why we have 3 now, and how often they are used standalone.

about the changelogs/changesets, I prefer to avoid external dependencies if possible and try to stay close to good community standards.

**Comment by connor-baer** [comment]
> I prefer the monorepo, but don't like the idea of just put them together with separate build systems

Each of these packages has slightly different requirements for how they're built. The components need additional plugins for Emotion, the code for the icons is generated programmatically, and the CLI targets Node instead of the browser. I think combining those build systems would complicate things instead of simplifying them.

> right now, will be just put 3 projects together, will save just the effort to keep track of 3 reps, but the pain point of 3 separate build systems, logs, dependencies, will be the same.

As I explained above, the separate build systems are a necessity and not really a pain point in my view. Separate dependencies is also a good thing for tree-shaking. Plus, each dependency can be used independently of the others (except Circuit UI which depends on the others).

I agree that a monorepo adds additional overhead in terms of tooling and maintenance and it remains to be seen whether the reduced effort for community management is worth the effort. 

I also see an opportunity in this. I can think of other SumUp projects and apps that might benefit from a monorepo approach and Circuit UI would be a good learning ground. 

> about the changelogs/changesets, I prefer to avoid external dependencies if possible and try to stay close to good community standards.

Can you elaborate on this, please? Which community standards are you referring to? `changesets`, the tool I'm proposing, is used by other popular libraries such as Emotion and maintained by Atlassian. It automates the process of generating GitHub releases and a changelog, which in my opinion meets community standards.

**Comment by felixjung** [comment]
I like this proposal a lot. Seems like the most reasonable way to go about managing everything related to Circuit UI in one place.

**Comment by nicosommi** [comment]
I see many benefits to start with this.

On one hand, we need to split packages so we can use them individually for the specific concern, like the design tokens and the icons.
On the other hand, the packages still have a strong relationship, this means that it will happen frequently (like in other domains too within the company) that a particular initiative will impact a few of these "semantically related" packages.
And it does, actually I create and see many pull request's that have an almost empty description and a link to the "main" pull request, which contains the full description.
So, the git-related work is one of the most important thing. This includes the review, the discussions in there, maybe even the commit and messages.

It is true that the tooling was not prepared to easily deal with this until some time ago, but things seem quite prepared now and major companies / open source projects are using it.

I also think there are other collateral benefits, like keep everything present.
It may not be the case in circuit, but it happens a lot that we create repositories that are after abandoned, or not present enough for frequent maintenance, because we just don't see them often enough. I think having them in the same repo could help with that.

If we have a good experience here maybe this practice can be easily spread in other repositories.
